-- Admin user creation is now handled by the application startup code
-- to avoid hardcoded passwords. The application will create the admin user
-- with a secure password from environment variables or generate a random one.