import type { ReactNode } from "react";
import type { ReportHistoryItem } from "./types";
import {
  formatDateLabel,
  formatDateTimeLabel,
  formatHistorySource,
  getHistoryFilename,
  getHistoryFormat,
  getHistoryReportType,
} from "./reportUtils";

interface ReportHistoryDetailsModalProps {
  item: ReportHistoryItem;
  downloadingHistoryId: number | null;
  onClose: () => void;
  onDownloadAgain: (item: ReportHistoryItem) => void;
  renderStatus: (value: string) => ReactNode;
}

export const ReportHistoryDetailsModal = ({
  item,
  downloadingHistoryId,
  onClose,
  onDownloadAgain,
  renderStatus,
}: ReportHistoryDetailsModalProps) => (
  <div
    className="screen-only fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"
    role="dialog"
    aria-modal="true"
    aria-labelledby="report-history-details-title"
    onClick={onClose}
  >
    <div
      className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-lg border border-gray-700 bg-gray-800 shadow-xl"
      onClick={(event) => event.stopPropagation()}
    >
      <div className="flex items-start justify-between border-b border-gray-700 p-6">
        <div>
          <h4
            id="report-history-details-title"
            className="text-lg font-semibold text-white"
          >
            Report History Details
          </h4>
          <p className="mt-1 text-sm text-gray-400">
            Audit details for report #{item.id}.
          </p>
        </div>
        <button
          onClick={onClose}
          className="rounded bg-gray-700 px-4 py-1 text-sm font-medium text-white hover:bg-gray-600"
        >
          Close
        </button>
      </div>

      <div className="space-y-6 p-6">
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
          {[
            {
              label: "Report Type",
              value: getHistoryReportType(item),
            },
            {
              label: "Format",
              value: getHistoryFormat(item),
            },
            {
              label: "Source",
              value: formatHistorySource(item),
            },
            {
              label: "Generated",
              value: formatDateTimeLabel(item.generatedAt),
            },
            {
              label: "Generated By",
              value: item.generatedBy?.name || item.generatedBy?.email || "Unknown",
            },
            {
              label: "Records",
              value: Number(item.recordCount || 0).toLocaleString(),
            },
          ].map((detail) => (
            <div
              key={detail.label}
              className="rounded border border-gray-700 bg-gray-900/50 p-4"
            >
              <div className="text-xs font-medium uppercase text-gray-500">
                {detail.label}
              </div>
              <div className="mt-1 text-sm font-medium text-gray-100">
                {detail.value}
              </div>
            </div>
          ))}
        </div>

        <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">
          <div className="rounded border border-gray-700 bg-gray-900/40 p-4">
            <h5 className="text-sm font-medium text-white">Saved Filters</h5>
            <dl className="mt-4 space-y-2 text-sm">
              <div className="flex justify-between gap-4">
                <dt className="text-gray-500">Date range</dt>
                <dd className="text-right text-gray-200">
                  {item.parameters?.startDate && item.parameters?.endDate
                    ? `${formatDateLabel(
                        item.parameters.startDate,
                      )} to ${formatDateLabel(item.parameters.endDate)}`
                    : "All Dates"}
                </dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-gray-500">Subject</dt>
                <dd className="text-right text-gray-200">
                  {item.parameters?.subjectLabel || "All Subjects"}
                </dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-gray-500">Class section</dt>
                <dd className="text-right text-gray-200">
                  {item.parameters?.classroomLabel || "All Sections"}
                </dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-gray-500">Scope</dt>
                <dd className="text-right text-gray-200">
                  {item.parameters?.scope ||
                    (item.generatedBy?.id
                      ? "User-accessible records"
                      : "Not recorded")}
                </dd>
              </div>
              {item.parameters?.scheduleName && (
                <div className="flex justify-between gap-4">
                  <dt className="text-gray-500">Schedule</dt>
                  <dd className="text-right text-gray-200">
                    {item.parameters.scheduleName}
                  </dd>
                </div>
              )}
            </dl>
          </div>

          <div className="rounded border border-gray-700 bg-gray-900/40 p-4">
            <h5 className="text-sm font-medium text-white">File and Status</h5>
            <dl className="mt-4 space-y-2 text-sm">
              <div className="flex justify-between gap-4">
                <dt className="text-gray-500">Status</dt>
                <dd>{renderStatus(item.status)}</dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-gray-500">Filename</dt>
                <dd className="text-right text-gray-200">
                  {getHistoryFilename(item)}
                </dd>
              </div>
              <div>
                <dt className="text-gray-500">Stored path</dt>
                <dd className="mt-1 break-all rounded bg-gray-950 p-2 text-xs text-gray-300">
                  {item.filePath || "Not recorded"}
                </dd>
              </div>
              <div>
                <dt className="text-gray-500">Status note</dt>
                <dd className="mt-1 rounded bg-gray-950 p-2 text-xs text-gray-300">
                  {item.errorMessage || "No error or status note recorded."}
                </dd>
              </div>
            </dl>
          </div>
        </div>

        <div className="rounded border border-gray-700 bg-gray-900/40 p-4">
          <h5 className="text-sm font-medium text-white">Selected Columns</h5>
          {item.parameters?.columns?.length ? (
            <div className="mt-4 flex flex-wrap gap-2">
              {item.parameters.columns.map((column) => (
                <span
                  key={column}
                  className="rounded border border-gray-700 bg-gray-800 px-2 py-1 text-xs text-gray-300"
                >
                  {column}
                </span>
              ))}
            </div>
          ) : (
            <p className="mt-2 text-sm text-gray-400">
              No custom column list was recorded for this report.
            </p>
          )}
        </div>

        <div className="flex justify-end gap-2">
          <button
            onClick={() => onDownloadAgain(item)}
            disabled={downloadingHistoryId === item.id}
            className="rounded bg-cyan-600 px-4 py-2 text-sm font-medium text-white hover:bg-cyan-700 disabled:bg-cyan-800"
          >
            {downloadingHistoryId === item.id
              ? "Downloading..."
              : "Download Again"}
          </button>
        </div>
      </div>
    </div>
  </div>
);

