import type { ReactNode } from "react";
import type {
  ClassroomOption,
  ReportParams,
  SubjectOption,
  SummaryItem,
} from "./types";
import { formatDateLabel, reportTypeLabels } from "./reportUtils";

interface PreviewPagination {
  page: number;
  limit: number;
  total: number;
}

interface ReportPreviewProps {
  reportParams: ReportParams;
  selectedSubject?: SubjectOption;
  selectedClassroom?: ClassroomOption;
  generatedByLabel: string;
  printTimestampLabel: string;
  previewData: Record<string, string>[];
  previewColumns: string[];
  previewLoading: boolean;
  pagination: PreviewPagination;
  overviewCards: SummaryItem[];
  autoRefresh: boolean;
  userRole?: string;
  setLastUpdated: (date: Date) => void;
  setPagination: React.Dispatch<React.SetStateAction<PreviewPagination>>;
  loadPreviewData: (page?: number) => Promise<void>;
  loadRealTimeStats: () => Promise<void>;
  renderStatus: (value: string) => ReactNode;
}

export const ReportPreview = ({
  reportParams,
  selectedSubject,
  selectedClassroom,
  generatedByLabel,
  printTimestampLabel,
  previewData,
  previewColumns,
  previewLoading,
  pagination,
  overviewCards,
  autoRefresh,
  userRole,
  setLastUpdated,
  setPagination,
  loadPreviewData,
  loadRealTimeStats,
  renderStatus,
}: ReportPreviewProps) => (
  <>
    <div className="print-report-preview bg-gray-800 rounded-lg shadow border border-gray-700">
      <div className="print-only print-report-header">
        <div className="print-report-brand">CLIRDEC:PRESENCE</div>
        <h1 className="print-report-title">
          {reportTypeLabels[reportParams.type]}
        </h1>
        <div className="print-report-meta">
          <div className="print-report-meta-item">
            <span>Report Type</span>
            <strong>{reportTypeLabels[reportParams.type]}</strong>
          </div>
          <div className="print-report-meta-item">
            <span>Date Range</span>
            <strong>
              {formatDateLabel(reportParams.startDate)} to{" "}
              {formatDateLabel(reportParams.endDate)}
            </strong>
          </div>
          <div className="print-report-meta-item">
            <span>Subject</span>
            <strong>
              {selectedSubject
                ? `${selectedSubject.code} - ${selectedSubject.name}`
                : "All Subjects"}
            </strong>
          </div>
          <div className="print-report-meta-item">
            <span>Class Section</span>
            <strong>
              {selectedClassroom
                ? `${selectedClassroom.name} - ${selectedClassroom.location}`
                : "All Sections"}
            </strong>
          </div>
          <div className="print-report-meta-item">
            <span>Generated</span>
            <strong>{printTimestampLabel}</strong>
          </div>
          <div className="print-report-meta-item">
            <span>Generated By</span>
            <strong>{generatedByLabel}</strong>
          </div>
        </div>
        <p className="print-report-summary">
          Live preview contains {previewData.length.toLocaleString()} rows from{" "}
          {pagination.total.toLocaleString()} matching records.
        </p>
        {userRole === "faculty" && (
          <p className="print-report-scope">
            Faculty scope: limited to your assigned schedules.
          </p>
        )}
      </div>
      <div className="print-only-grid print-overview-grid">
        {overviewCards.map((item) => (
          <div key={item.label} className="print-overview-card">
            <div className="print-overview-value">{item.value}</div>
            <div className="print-overview-label">{item.label}</div>
          </div>
        ))}
      </div>
      <div className="screen-only px-6 py-4 border-b border-gray-700">
        <div className="flex items-center justify-between">
          <div>
            <h4 className="text-lg font-medium text-white">
              Live Report Preview
            </h4>
            <p className="text-sm text-gray-300">
              {reportTypeLabels[reportParams.type]} with{" "}
              {pagination.total.toLocaleString()} matching rows
              {autoRefresh && (
                <span className="ml-2 text-cyan-400">• Auto-refreshing</span>
              )}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => {
                setLastUpdated(new Date());
                window.setTimeout(() => window.print(), 0);
              }}
              className="bg-gray-700 hover:bg-gray-600 text-white px-3 py-1 rounded text-sm font-medium"
            >
              Print Preview
            </button>
            <button
              onClick={() => {
                loadPreviewData();
                loadRealTimeStats();
                setLastUpdated(new Date());
              }}
              className="bg-gray-700 hover:bg-gray-600 text-white px-3 py-1 rounded text-sm font-medium flex items-center space-x-1"
            >
              <span>🔄</span>
              <span>Refresh</span>
            </button>
          </div>
        </div>
      </div>
      <div className="print-report-table-wrap overflow-x-auto">
        <table className="print-report-table min-w-full divide-y divide-gray-700">
          <thead className="bg-gray-900">
            <tr>
              {previewColumns.map((column) => (
                <th
                  key={column}
                  className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                >
                  {column}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="bg-gray-800 divide-y divide-gray-700">
            {previewLoading ? (
              <tr>
                <td
                  colSpan={previewColumns.length}
                  className="px-6 py-10 text-center text-sm text-gray-400"
                >
                  Loading preview...
                </td>
              </tr>
            ) : previewData.length === 0 ? (
              <tr>
                <td
                  colSpan={previewColumns.length}
                  className="px-6 py-10 text-center text-sm text-gray-400"
                >
                  No preview rows available for the selected filters.
                </td>
              </tr>
            ) : (
              previewData.map((record, index) => (
                <tr
                  key={`${record["Session ID"] || record["Student ID"] || "row"}-${index}`}
                >
                  {previewColumns.map((column) => (
                    <td
                      key={column}
                      className="px-6 py-4 whitespace-nowrap text-sm text-gray-300"
                    >
                      {column === "Status"
                        ? renderStatus(record[column])
                        : record[column] || "-"}
                    </td>
                  ))}
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
      <div className="print-only print-report-footer">
        <span>Confidential Academic Record</span>
        <span>Page printed {printTimestampLabel}</span>
        <span>
          Generated from live preview; exports may include all matching records.
        </span>
      </div>
    </div>

    {pagination.total > pagination.limit && (
      <div className="screen-only flex items-center justify-between px-6 py-3 bg-gray-800 border-t border-gray-700">
        <div className="text-sm text-gray-400">
          Showing {(pagination.page - 1) * pagination.limit + 1} to{" "}
          {Math.min(pagination.page * pagination.limit, pagination.total)} of{" "}
          {pagination.total} results
        </div>
        <div className="flex items-center space-x-2">
          <button
            onClick={() => {
              const newPage = pagination.page - 1;
              setPagination((prev) => ({ ...prev, page: newPage }));
              loadPreviewData(newPage);
            }}
            disabled={pagination.page <= 1}
            className="px-3 py-1 text-sm bg-gray-700 text-gray-300 rounded hover:bg-gray-600 disabled:bg-gray-800 disabled:text-gray-500"
          >
            Previous
          </button>
          <span className="text-sm text-gray-400">
            Page {pagination.page} of{" "}
            {Math.ceil(pagination.total / pagination.limit)}
          </span>
          <button
            onClick={() => {
              const newPage = pagination.page + 1;
              setPagination((prev) => ({ ...prev, page: newPage }));
              loadPreviewData(newPage);
            }}
            disabled={
              pagination.page >= Math.ceil(pagination.total / pagination.limit)
            }
            className="px-3 py-1 text-sm bg-gray-700 text-gray-300 rounded hover:bg-gray-600 disabled:bg-gray-800 disabled:text-gray-500"
          >
            Next
          </button>
        </div>
      </div>
    )}

    <div className="screen-only grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
      {overviewCards.map((item) => (
        <div
          key={item.label}
          className="bg-gray-800 rounded-lg p-4 border border-gray-700"
        >
          <div className="text-center">
            <div className="text-2xl font-bold text-white">{item.value}</div>
            <div className="text-sm text-gray-400">{item.label}</div>
            <div className="text-xs text-gray-500 mt-1">Selected filters</div>
          </div>
        </div>
      ))}
    </div>
  </>
);
