import type { Dispatch, SetStateAction } from "react";
import type { ReportHistoryFilters, ReportHistoryItem } from "./types";
import {
  formatDateLabel,
  formatHistorySource,
  reportTypeLabels,
  toTitle,
} from "./reportUtils";

interface ReportHistoryPagination {
  page: number;
  limit: number;
  total: number;
}

interface ReportHistoryProps {
  reportHistory: ReportHistoryItem[];
  reportHistoryFilters: ReportHistoryFilters;
  reportHistoryPagination: ReportHistoryPagination;
  userRole?: string;
  exportingHistory: boolean;
  downloadingHistoryId: number | null;
  setReportHistoryFilters: Dispatch<SetStateAction<ReportHistoryFilters>>;
  loadReportHistory: (
    filters?: ReportHistoryFilters,
    page?: number,
  ) => Promise<void>;
  resetReportHistoryFilters: () => void;
  clearReportHistoryFilter: (key: keyof ReportHistoryFilters) => void;
  exportReportHistoryCsv: () => Promise<void>;
  setSelectedHistoryItem: (item: ReportHistoryItem) => void;
  handleDownloadHistoryReport: (item: ReportHistoryItem) => Promise<void>;
}

export const ReportHistory = ({
  reportHistory,
  reportHistoryFilters,
  reportHistoryPagination,
  userRole,
  exportingHistory,
  downloadingHistoryId,
  setReportHistoryFilters,
  loadReportHistory,
  resetReportHistoryFilters,
  clearReportHistoryFilter,
  exportReportHistoryCsv,
  setSelectedHistoryItem,
  handleDownloadHistoryReport,
}: ReportHistoryProps) => {
  const reportHistoryPageCount = Math.max(
    1,
    Math.ceil(reportHistoryPagination.total / reportHistoryPagination.limit),
  );
  const reportHistoryStart =
    reportHistoryPagination.total === 0
      ? 0
      : (reportHistoryPagination.page - 1) * reportHistoryPagination.limit + 1;
  const reportHistoryEnd = Math.min(
    reportHistoryPagination.page * reportHistoryPagination.limit,
    reportHistoryPagination.total,
  );
  const activeHistoryFilterChips = [
    reportHistoryFilters.type && {
      key: "type",
      label: `Type: ${reportTypeLabels[reportHistoryFilters.type]}`,
    },
    reportHistoryFilters.format && {
      key: "format",
      label: `Format: ${reportHistoryFilters.format.toUpperCase()}`,
    },
    reportHistoryFilters.source && {
      key: "source",
      label: `Source: ${toTitle(reportHistoryFilters.source)}`,
    },
    reportHistoryFilters.status && {
      key: "status",
      label: `Status: ${toTitle(reportHistoryFilters.status)}`,
    },
    reportHistoryFilters.startDate && {
      key: "startDate",
      label: `From: ${formatDateLabel(reportHistoryFilters.startDate)}`,
    },
    reportHistoryFilters.endDate && {
      key: "endDate",
      label: `To: ${formatDateLabel(reportHistoryFilters.endDate)}`,
    },
    reportHistoryFilters.generatedBy.trim() && {
      key: "generatedBy",
      label: `Generated by: ${reportHistoryFilters.generatedBy.trim()}`,
    },
  ].filter(Boolean) as { key: keyof ReportHistoryFilters; label: string }[];

  return (
    <div className="screen-only bg-gray-800 rounded-lg p-4 border border-gray-700">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h4 className="text-lg font-medium text-white">Report History</h4>
          <p className="text-sm text-gray-400">
            {reportHistoryPagination.total.toLocaleString()} matching reports
            with filters, format, owner, and row count.
          </p>
        </div>
        <div className="flex flex-wrap gap-2">
          {userRole === "admin" && (
            <button
              onClick={exportReportHistoryCsv}
              disabled={exportingHistory}
              className="bg-gray-700 hover:bg-gray-600 disabled:bg-gray-800 text-white px-4 py-1 rounded text-sm"
            >
              {exportingHistory ? "Exporting..." : "Export History CSV"}
            </button>
          )}
          <button
            onClick={() =>
              loadReportHistory(
                reportHistoryFilters,
                reportHistoryPagination.page,
              )
            }
            className="bg-gray-700 hover:bg-gray-600 text-white px-4 py-1 rounded text-sm"
          >
            Refresh
          </button>
        </div>
      </div>
      <div className="mb-4 rounded-md border border-gray-700 bg-gray-900/40 p-4">
        <div className="mb-4 flex flex-col gap-1 md:flex-row md:items-end md:justify-between">
          <div>
            <h5 className="text-sm font-medium text-white">History Filters</h5>
            <p className="text-xs text-gray-500">
              Find reports by type, format, source, status, owner, or date.
            </p>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => loadReportHistory(reportHistoryFilters, 1)}
              className="rounded bg-cyan-600 px-4 py-2 text-xs font-medium text-white hover:bg-cyan-700"
            >
              Apply Filters
            </button>
            <button
              onClick={resetReportHistoryFilters}
              className="rounded bg-gray-700 px-4 py-2 text-xs font-medium text-gray-200 hover:bg-gray-600"
            >
              Reset
            </button>
          </div>
        </div>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3 xl:grid-cols-6">
          <div>
            <label
              htmlFor="history-filter-type"
              className="mb-1 block text-xs font-medium text-gray-400"
            >
              Report Type
            </label>
            <select
              id="history-filter-type"
              value={reportHistoryFilters.type}
              onChange={(event) =>
                setReportHistoryFilters((current) => ({
                  ...current,
                  type: event.target.value as ReportHistoryFilters["type"],
                }))
              }
              className="w-full rounded-md border border-gray-600 bg-gray-700 px-4 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
            >
              <option value="">All types</option>
              <option value="attendance">Attendance</option>
              <option value="students">Students</option>
              <option value="classroom">Classroom</option>
            </select>
          </div>
          <div>
            <label
              htmlFor="history-filter-format"
              className="mb-1 block text-xs font-medium text-gray-400"
            >
              Format
            </label>
            <select
              id="history-filter-format"
              value={reportHistoryFilters.format}
              onChange={(event) =>
                setReportHistoryFilters((current) => ({
                  ...current,
                  format: event.target.value as ReportHistoryFilters["format"],
                }))
              }
              className="w-full rounded-md border border-gray-600 bg-gray-700 px-4 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
            >
              <option value="">All formats</option>
              <option value="csv">CSV</option>
              <option value="xlsx">Excel</option>
              <option value="pdf">PDF</option>
            </select>
          </div>
          <div>
            <label
              htmlFor="history-filter-source"
              className="mb-1 block text-xs font-medium text-gray-400"
            >
              Source
            </label>
            <select
              id="history-filter-source"
              value={reportHistoryFilters.source}
              onChange={(event) =>
                setReportHistoryFilters((current) => ({
                  ...current,
                  source: event.target.value as ReportHistoryFilters["source"],
                }))
              }
              className="w-full rounded-md border border-gray-600 bg-gray-700 px-4 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
            >
              <option value="">All sources</option>
              <option value="manual">Manual export</option>
              <option value="email">Email export</option>
              <option value="quick">Quick report</option>
              <option value="scheduled">Scheduled report</option>
              <option value="download-again">Download again</option>
            </select>
          </div>
          <div>
            <label
              htmlFor="history-filter-status"
              className="mb-1 block text-xs font-medium text-gray-400"
            >
              Status
            </label>
            <select
              id="history-filter-status"
              value={reportHistoryFilters.status}
              onChange={(event) =>
                setReportHistoryFilters((current) => ({
                  ...current,
                  status: event.target.value as ReportHistoryFilters["status"],
                }))
              }
              className="w-full rounded-md border border-gray-600 bg-gray-700 px-4 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
            >
              <option value="">All statuses</option>
              <option value="completed">Completed</option>
              <option value="failed">Failed</option>
              <option value="pending">Pending</option>
            </select>
          </div>
          <div>
            <label
              htmlFor="history-filter-start"
              className="mb-1 block text-xs font-medium text-gray-400"
            >
              From
            </label>
            <input
              id="history-filter-start"
              type="date"
              value={reportHistoryFilters.startDate}
              onChange={(event) =>
                setReportHistoryFilters((current) => ({
                  ...current,
                  startDate: event.target.value,
                }))
              }
              className="w-full rounded-md border border-gray-600 bg-gray-700 px-4 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
            />
          </div>
          <div>
            <label
              htmlFor="history-filter-end"
              className="mb-1 block text-xs font-medium text-gray-400"
            >
              To
            </label>
            <input
              id="history-filter-end"
              type="date"
              value={reportHistoryFilters.endDate}
              onChange={(event) =>
                setReportHistoryFilters((current) => ({
                  ...current,
                  endDate: event.target.value,
                }))
              }
              className="w-full rounded-md border border-gray-600 bg-gray-700 px-4 py-2 text-sm text-white focus:outline-none focus:ring-2 focus:ring-cyan-500"
            />
          </div>
          <div className="md:col-span-3 xl:col-span-6">
            <label
              htmlFor="history-filter-generated-by"
              className="mb-1 block text-xs font-medium text-gray-400"
            >
              Generated By
            </label>
            <input
              id="history-filter-generated-by"
              type="text"
              value={reportHistoryFilters.generatedBy}
              onChange={(event) =>
                setReportHistoryFilters((current) => ({
                  ...current,
                  generatedBy: event.target.value,
                }))
              }
              placeholder="Name, email, or user ID"
              className="w-full rounded-md border border-gray-600 bg-gray-700 px-4 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-cyan-500"
            />
          </div>
        </div>
      </div>
      {activeHistoryFilterChips.length > 0 && (
        <div className="mb-4 flex flex-wrap gap-2">
          {activeHistoryFilterChips.map((chip) => (
            <button
              key={chip.key}
              onClick={() => clearReportHistoryFilter(chip.key)}
              className="rounded border border-cyan-800 bg-cyan-950/40 px-2 py-1 text-xs font-medium text-cyan-100 hover:bg-cyan-900/60"
              title="Clear this filter"
            >
              {chip.label} x
            </button>
          ))}
        </div>
      )}
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-700">
          <thead className="bg-gray-900">
            <tr>
              {[
                "Type",
                "Filters",
                "Format",
                "Generated By",
                "Timestamp",
                "Records",
                "Actions",
              ].map((column) => (
                <th
                  key={column}
                  className="px-4 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                >
                  {column}
                </th>
              ))}
            </tr>
          </thead>
          <tbody className="bg-gray-800 divide-y divide-gray-700">
            {reportHistory.length === 0 ? (
              <tr>
                <td
                  colSpan={7}
                  className="px-4 py-8 text-center text-sm text-gray-400"
                >
                  No reports match the current history filters.
                </td>
              </tr>
            ) : (
              reportHistory.map((item) => (
                <tr key={item.id}>
                  <td className="px-4 py-3 text-sm text-white capitalize">
                    {item.reportType}
                    <div className="text-xs text-gray-500">
                      {formatHistorySource(item)}
                    </div>
                  </td>
                  <td className="px-4 py-3 text-sm text-gray-300">
                    {[
                      item.parameters?.subjectLabel || "All Subjects",
                      item.parameters?.classroomLabel || "All Sections",
                      item.parameters?.startDate && item.parameters?.endDate
                        ? `${item.parameters.startDate} to ${item.parameters.endDate}`
                        : "All Dates",
                    ].join(" | ")}
                  </td>
                  <td className="px-4 py-3 text-sm text-cyan-300 uppercase">
                    {item.parameters?.format ||
                      item.filePath?.split(".").pop() ||
                      "-"}
                  </td>
                  <td className="px-4 py-3 text-sm text-gray-300">
                    {item.generatedBy?.name || "Unknown"}
                  </td>
                  <td className="px-4 py-3 text-sm text-gray-300 whitespace-nowrap">
                    {new Date(item.generatedAt).toLocaleString()}
                  </td>
                  <td className="px-4 py-3 text-sm text-gray-300">
                    {Number(item.recordCount || 0).toLocaleString()}
                  </td>
                  <td className="px-4 py-3 text-sm text-gray-300">
                    <div className="flex gap-2">
                      <button
                        onClick={() => setSelectedHistoryItem(item)}
                        className="bg-gray-700 hover:bg-gray-600 text-white px-4 py-1 rounded text-xs font-medium whitespace-nowrap"
                      >
                        Details
                      </button>
                      <button
                        onClick={() => handleDownloadHistoryReport(item)}
                        disabled={downloadingHistoryId === item.id}
                        className="bg-gray-700 hover:bg-gray-600 disabled:bg-gray-800 text-white px-4 py-1 rounded text-xs font-medium whitespace-nowrap"
                      >
                        {downloadingHistoryId === item.id
                          ? "Downloading..."
                          : "Download Again"}
                      </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
      <div className="mt-4 flex flex-col gap-4 border-t border-gray-700 pt-4 text-sm text-gray-400 md:flex-row md:items-center md:justify-between">
        <div>
          Showing {reportHistoryStart.toLocaleString()} to{" "}
          {reportHistoryEnd.toLocaleString()} of{" "}
          {reportHistoryPagination.total.toLocaleString()} matching reports
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() =>
              loadReportHistory(
                reportHistoryFilters,
                reportHistoryPagination.page - 1,
              )
            }
            disabled={reportHistoryPagination.page <= 1}
            className="rounded bg-gray-700 px-4 py-1 text-sm text-gray-300 hover:bg-gray-600 disabled:bg-gray-800 disabled:text-gray-500"
          >
            Previous
          </button>
          <span>
            Page {reportHistoryPagination.page} of {reportHistoryPageCount}
          </span>
          <button
            onClick={() =>
              loadReportHistory(
                reportHistoryFilters,
                reportHistoryPagination.page + 1,
              )
            }
            disabled={reportHistoryPagination.page >= reportHistoryPageCount}
            className="rounded bg-gray-700 px-4 py-1 text-sm text-gray-300 hover:bg-gray-600 disabled:bg-gray-800 disabled:text-gray-500"
          >
            Next
          </button>
        </div>
      </div>
    </div>
  );
};

