export declare const users: any;
export declare const students: any;
export declare const classrooms: any;
export declare const subjects: any;
export declare const schedules: any;
export declare const classSessions: any;
export declare const attendanceRecords: any;
export declare const computers: any;
export declare const computerAssignments: any;
export declare const iotDevices: any;
export declare const usersRelations: any;
export declare const studentsRelations: any;
export declare const classroomsRelations: any;
export declare const subjectsRelations: any;
export declare const schedulesRelations: any;
export declare const classSessionsRelations: any;
export declare const attendanceRecordsRelations: any;
export declare const computersRelations: any;
export declare const computerAssignmentsRelations: any;
export declare const iotDevicesRelations: any;
export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Student = typeof students.$inferSelect;
export type NewStudent = typeof students.$inferInsert;
export type Classroom = typeof classrooms.$inferSelect;
export type NewClassroom = typeof classrooms.$inferInsert;
export type Subject = typeof subjects.$inferSelect;
export type NewSubject = typeof subjects.$inferInsert;
export type Schedule = typeof schedules.$inferSelect;
export type NewSchedule = typeof schedules.$inferInsert;
export type ClassSession = typeof classSessions.$inferSelect;
export type NewClassSession = typeof classSessions.$inferInsert;
export type AttendanceRecord = typeof attendanceRecords.$inferSelect;
export type NewAttendanceRecord = typeof attendanceRecords.$inferInsert;
export type Computer = typeof computers.$inferSelect;
export type NewComputer = typeof computers.$inferInsert;
export type ComputerAssignment = typeof computerAssignments.$inferSelect;
export type NewComputerAssignment = typeof computerAssignments.$inferInsert;
export type IotDevice = typeof iotDevices.$inferSelect;
export type NewIotDevice = typeof iotDevices.$inferInsert;
//# sourceMappingURL=schema.d.ts.map